version: "3.9"

services:
  api:
    build:
      context: ./api
    ports:
      - "8080:8080"
    container_name: yifu-api
    depends_on:
      - postgres
  postgres:
    image: postgres:16.0-alpine3.17
    container_name: yifu-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

